// JavaScript Document
[
	{
		newG:[
			'电信一区',
			'元素殿堂',
			'欢迎进驻！',
			'www.aa.com',
			'a1'
	],
		newG1:[
			'网通一区',
			'雷霆之怒',
			'欢迎进驻！',
			'www.bb.com',
			'a2'
		],
		count:[
			'203',
			'www.baidu.com'
		],
		play:[
			{
				'name1':'女武神的密宝',
				'name1_herf':'www.baidu.com',
				'name1_show':'进行中',
				'game1':'神谕者的成长礼',
				'game1_herf':'www.baidu.com',
				'game1_show':'进行中',
				'game2':'女神赐福助力成长，老友归来大礼相赠',
				'game2_show':'进行中',
				'game2_herf':'www.baidu.com',
				'game3':'赫尔墨斯的宝库，尼凯亚大陆奇珍异宝',
				'game3_show':'进行中',
				'game3_herf':'www.baidu.com',
				'game4':'绑定畅游+，送十格背包',
				'game4_show':'进行中',
				'game4_herf':'www.baidu.com',
				'game5':'每日登陆有惊喜',
				'game5_show':'进行中',
				'game5_herf':'www.baidu.com',
			}
		]
	}
]
